import { TodoItem } from './TODOList/types';

// 模拟数据存储
export const mockTodos: TodoItem[] = [
  {
    id: '1',
    content: '完成项目文档',
    color: '#667eea',
    description: '编写技术文档和用户手册',
    startDate: '2024-01-15',
    endDate: '2024-01-20',
    completed: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '2',
    content: '代码审查',
    color: '#00d4aa',
    description: '审查团队成员提交的代码',
    startDate: '2024-01-16',
    endDate: '2024-01-17',
    completed: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '3',
    content: '准备演示',
    color: '#ef4444',
    description: '为客户演示准备材料',
    startDate: '2024-01-18',
    endDate: '2025-06-22',
    completed: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '4',
    content: '哈牛魔',
    color: '#667eea',
    description: '编写技术文档和用户手册',
    startDate: '2024-01-15',
    endDate: '2025-06-22',
    completed: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '5',
    content:
      '摸南北绿豆摸南北绿豆摸南北绿豆摸南北绿豆摸南北绿豆摸南北绿豆摸南北绿豆摸南北绿豆摸南北绿豆摸南北绿豆',
    color: '#00d4aa',
    description: '审查团队成员提交的代码',
    startDate: '2024-01-16',
    endDate: '2025-06-23',
    completed: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '6',
    content: '哈基米',
    color: '#ef4444',
    description: '为客户演示准备材料',
    startDate: '2024-01-18',
    endDate: '2025-06-22',
    completed: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];
